on: [push]

jobs:
  main_job:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: npm i
      - name: Start Patch
        uses: ./
        with:
          base_file_path: './template/base.md'
          patch_file_path: './template/patch'
          output_file_path: './CODE_OF_CONDUCT.md'
      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: "Applied the patch to the base Code of Conduct."
          branch: actions/patch-code-of-conduct  # Custom branch *just* for this Action.
          commit-message: 'doc: update Code of Conduct'
          title: 'doc: update Code of Conduct'
